[package]
name = "octtree"
version = "0.1.0"
edition = "2024"

[dependencies]
pathmap = { path="../..", features=["arena_compact", "act_counters"] }
memmap2 = { version="0.9.5" }
anyhow = "1.0.98"
pasture-core = "0.5.0"
pasture-io = "0.5.0"
rand = "0.9.1"